CREATE DATABASE MysqlTask;
use MysqlTask;
CREATE TABLE details (
  id int  NOT NULL,School_name varchar(48) NOT NULL,College_name varchar(20) NOT NULL,Graduation varchar(20),firstName varchar(50) NOT NULL,secondName varchar(50) NOT NULL,
  father_name varchar(20) NOT NULL,Mother_name varchar(20)NOT NULL,grandfather_name varchar(20)not null,age int,pin_code int,city varchar(50)NOT NULL,phone varchar(20) NOT NULL,
  email  varchar(100) NOT NULL,State varchar(300) NOT NULL,experience varchar(300)NOT NULL,material_status varchar(10)NOT NULL,facebook varchar(20) NOT NULL,
  g_password varchar(64) NOT NULL,company varchar(20),PRIMARY KEY (`phone`));
  
  SELECT * FROM details;
  DROP TABLE details;
  SELECT * FROM details order by id;
  
INSERT INTO details VALUES(1,'GHPS MATHIKAI','PPC','BE','SRISHAM','S M','PRAKASH','SANGEETHA','LAXMINARAYANA',20,577452,'SHIMOGA',8277738399,'srishamsm6@gmail.com','KARNATAKA',2,'SINGLE','SRISHAMSAMPEKATTE','@123','APPLE');
INSERT INTO details VALUES(2,'GHPS BANEKAL','HSKP','BE','ARUN','B V','KASHINATH','KAVITA','RUDRAPPA',21,58214,'BELLARY',9620753670,'arunbv.xworkz@gmail.com','KARNATAKA',3,'COMMITED','ARUN BV','@124','MICROSOFT');
INSERT INTO details VALUES(3,'GHPS CHANNPATTANA','BDVT','BE','CHAITRA','M','MANJUNATH','NETRAVATI','MALLESHAYYA',21,562138,'RAMNAGR',7996509441,'chaitram.xworkz@gmail.com','KARNATAKA',1,'SINGLE','CHAITRAM','@125','INFOSYS');
INSERT INTO details VALUES(4,'GHPS HOSAHALLI','govt poly,Hosadurga','BE','HARISH','B V','RAJANNA','PUSHPA','BASAVARAJ',22,577542,'CHITRADURGA',9900778949,'harish.xworkz@gmail.com','KARNATAKA',1,'COMMITED','HARISH HR','@125','TCS');
INSERT INTO details VALUES(5,'GHPS VIJAYAVADA','NPC','BTECH','JOSHELA','S','VENKATRAMANA','PADMAJA','NARASIMHA',22,583201,'VIJAYAVADA',7483618780,'saijosheela.xworkz@gmail.com','ANDRAPADESH',1,'COMMITED','SAI JOSHEEELA S','@126','HCL');
INSERT INTO details VALUES(6,'GHPS RIPPONPET','Govt Ripponpet','MCA','NAVYA','N K','K V ','GEETHA','Narayana',20,577426,'SHIMOGA',9620753674,'navyank.xworkz@gmail.com','KARNATAKA',3,'MARRIED','SHRI NK','@126','GALIGAR');
INSERT INTO details VALUES(7,'GHPS HOSADURGA ','KIT','BE','SHASHANK','K B','BASAVARAJAPPA','VIMALA','VISWESWARAYYA',21,577515,'HOSADURGA',908120838,'shashank.xworkz@gmail.com','KARNATAKA',6,'COMMITED','SHASHANK SHASH','@127','GOOGLE');
INSERT INTO details VALUES(8,'GHPS NALANDA','KALPATARU','BE','SANJAY ','S','SHASHIKUMAR','SUDHA','RANGAPPA',23,572201,'TUMKUR',7483360070,'sanjays.xworkz@gmail.com','KARNATAKA',2,'COMMITED','SANJAY S','@128','HP');
INSERT INTO details VALUES(9,'GHPS GANJIGERE','RJSP','BE','NATARAJ','S','SANNAPPA','LALITHAMMA','NATTU',23,577533,'CHITRADURGA',9620753256,'natarajs.xworkz@gmail.com','KARNATAKA',2,'COMMITED','NATARAJ S','@129','FIRELATA');
INSERT INTO details VALUES(10,'NEW ENGLISH SCHOOL','K L E','BE','SHUBHAM','GARVE','ARAVIND','SUNITA','SUBBARAO',24,416115,'KOLLAPUR',88877484,'shubhamgarve.xworkz@gmail.com','KARNATAKA',2,'SINGLE','SHIMOSIS','@310','XWORKZ');
INSERT INTO details VALUES(11,'GHPS VADDINKOPPA','CHAITANYA','M COM','MADHU','RAO','ARAVIND','ARUNDATI','NARASIMHA',27,581418,'U K',9632080344,'madhurao@gmail.com','ANDRAPRADESH',4,'SINGLE','MADHU RAO','@132','KARNATAKA BANK');
INSERT INTO details VALUES(12,'PBVK','PPC ADMAR','M B A','SUMANTH','O R','RAMANANDA','SAVITHA','KRISHNA',23,577418,'SHIMOGA',9481535704,'sumanthor.xworkz@gmail.com','KARNATAKA',1,'SINGLE','SUMANTH SHARMA','@133','KOTAK MAHINDRA');
INSERT INTO details VALUES(13,'GHPS MATHIKAI','PPC ADAMR','BE','VARUN','D M','MAHABALESHWAR','VANI','TIMMNNA',23,577452,'SHIVAMOGGA',9632898979,'varundm.xworkz@gmail.com','KARNATAKA',4,'SINGLE','VARN D M ','@134','KDCC');
INSERT INTO details VALUES(14,'GHPS NITTUR','MGM','BEEC','ATRI','K S ','SATHYANARAYNA','SUMALATHA','MAHABALESHWAR',24,577418,'UDUPI',963278547,'atriks.xworkz@gmail.com','KARNATAKA',6,'SINGLE','ATRI KS','@135','ORACLE');
INSERT INTO details VALUES(15,'GHPS SAGAR','GOVT PU','DIPLOMA','SHRIKANTH','O R','RAMANAND','SAVITA','KRISHNA',29,577452,'BELLARY',9743445720,'shrikanthor@gmail.com','KARNATAKA',8,'MARRIED','SHRIKANTH','@136','RAITA MITRA');
INSERT INTO details VALUES(16,'MATA AMRUTHANANDA MAI','PPC ADAMAR','BCA','ABHIRAM','S','SURYA','SUMATHI','RAMACHANDRAYYA',16,577452,'SHIMOGA',9448722122,'abhiramu@gmail.com','KARNATAKA',0,'SINGLE','ABHI RAMU','@157','NTT DATA');
INSERT INTO details VALUES(17,'GHPS MUDHOL','BGMIT','BE','AKSHAY','JOSHI','RAMKRISHANA','KAVITA','RAMAPPA',24,58214,'BIDAR',9620753669,'akshayjoshi.xworkz@gmail.com','KARNATAKA',0,'COMMITED','AKSYAY JOSHI','@124','CGI');
INSERT INTO details VALUES(18,'RAMKRISHNA VIDYALAYA','SJC','LLB','POORNA','S','SHESHAGIRI','ASHA','LAXMINARAYANA',18,577418,'HOSANAGARA',944872212,'poornas@gmail.com','KARNATAKA',0,'SINGLE','POORNA S','@145','DELL');
INSERT INTO details VALUES(19,'SAINTH JOSEPH','SDMIT',' C A','POOJA','S N','NAGARAJ','MOOKAMBIKA','BASKAR',28,581417,'CKM',8171647570,'poojasn@gmail.com','KARNATAKA',8,'MARRIED','POOOOH','@578','A ONE');
INSERT INTO details VALUES(20,'SMPS GOLIHOLE','BANDARKARS','C S ','RAMACHANDRA','BHAT','LAXMINARAYANA','KAVITA','RAMARAO',26,58214,'UDUPI',9620753687,'ramchandrabhat@gmail.com','KARNATAKA',7,'SINGLE','RAMACHANDRA BHAT','@136','BOSCH');

SELECT * FROM details where firstName ="AKSHAY" AND  id=17;
SELECT * FROM details where human_Name ="Navya" OR Slno =1;
SELECT * FROM details where id in(1,2,3);
SELECT * FROM details where id not in(1,2,3);
SELECT * FROM details WHERE id between 2 and 8;


SELECT COUNT(*) AS Mother_name from details;
SELECT SUM(age) from details;
SELECT MAX(age) from details;
SELECT MIN(age) from details;
SELECT AVG(age) from details;












